SkillsFundingAgency/tl-results-prototype

- app/routes/routes-1-6.js
- app/views/1-6/AO/data/Accounts_v1.5.csv
- app/views/1-6/AO/data/TLevels_v1.6.csv
- app/views/1-6/AO/data/specialisms_v1.6.csv
- app/views/1-6/AO/report-tlevel-issue.html
- app/views/1-6/AO/tlevel-details.html
- app/views/1-6/AO/tlevel-select.html
- app/views/1-6/AO/verify-tlevel-details.html
- app/views/1-6/AO/view-all-tlevels.html
- app/views/1-6/Verification/add-roles-all.html
- TLRC - 248 - Dev - Changes to content and loading dummy user account
> TLRC - 222 - Create MVP Prototype

- app/routes/routes-1-17.js
- app/views/1-17/Research/search-failed-notadded.html
- app/views/1-17/Research/student-records.html
- app/views/1-17/Research/tlevels-start.html
- app/views/1-17/dynamic/change-ip-result-successful.html
- app/views/1-17/dynamic/search-failed-notadded.html
- app/views/1-17/dynamic/send-learner.html
- app/views/1-17/dynamic/student-results.html
- app/views/1-17/dynamic/tlevels-start.html
> Feature/sprint 30.8

- app/routes/routes-1-18.js
- app/views/1-17/AO/add-learner-q1-ulnAlreadyAdded.html
- app/views/1-17/AO/record-entries3.html
- app/views/1-17/AO/send-learner.html
- app/views/1-17/data/Accounts_v17.csv
- app/views/1-17/dynamic/add-learner-q1-ulnAlreadyAdded.html
- app/views/1-18/Research/add-learner-q1-ulnAlreadyAdded.html
- app/views/1-18/Research/add-learner-q4-check.html
- app/views/1-18/Research/q1-learners-details-change-no.html
- app/views/1-18/Research/q2-quals-change-no.html
- app/views/1-18/Research/q2-quals.html
- app/views/1-18/Research/q3-tq-components-change-no.html
- app/views/1-18/Research/q3-tq-components-no.html
- app/views/1-18/Research/q3-tq-components.html
- app/views/1-18/Research/q4-address-change-no.html
- app/views/1-18/Research/q4-address-no.html
- app/views/1-18/Research/q5-check.html
- app/views/1-18/Research/q5-check1.html
- app/views/1-18/Research/statement.html
- app/views/1-18/data/Accounts_v18.csv
- app/views/index.html
> Feature/sprint 31.0

- app/views/1-18/dynamic/add-address-confirmation.html
- app/views/1-18/dynamic/learner-details-requestpending.html
- app/views/1-18/dynamic/learner-ulnNotExist.html
- app/views/1-18/dynamic/missing-address.html
- app/views/1-18/dynamic/statement.html
Confirmation screen changes - copy changed and CTA added. Missing pages added back in
> Postal Address Changes

- app/views/1-20/dynamic/cancel-request.html
- app/views/1-20/dynamic/check-your-answers.html
- app/views/1-20/dynamic/learners-details-change.html
- app/views/1-20/dynamic/search-learner.html
- app/views/1-20/dynamic/statement.html
Content updates (missing question mark / apostrophe )
> 1-20 SoA Content updates

- app/views/1-20/dynamic/search-learner.html
removed duplicate ULN sentence
> 1-20 - removal of duplicate sentence

- app/routes.js
- app/views/1-20/dynamic/add-learner-q1-uln.html
- app/views/1-20/dynamic/add-learner-q1-ulnAlreadyAdded.html
- app/views/1-20/dynamic/add-learner-q1-ulnNotExist.html
- app/views/1-20/dynamic/add-learner-q2-em.html
- app/views/1-20/dynamic/learner-details-noresults.html
- app/views/1-20/dynamic/result-entries1.html
- app/views/1-20/dynamic/student-results.html
Updates to the Add T level record journey so that its shows ULN's that have already been added
> 1-20 SoA Updates

- app/routes.js
- app/views/1-20/dynamic/check-your-answers.html
- app/views/1-20/dynamic/learner-details-requestpending.html
- app/views/1-20/dynamic/org-address-present.html
Fixed error so that when department is updated it is shown in the check and submit page. Date in SoA requested already page fixed
> 1-20 SoA - department fix

- app/routes.js
- app/views/1-19/dynamic/change-specialism-result.html
- app/views/1-19/dynamic/no-learner-found.html
- app/views/1-19/dynamic/reviews-and-appeals.html
- app/views/1-20/dynamic/add-address-confirm-address.html
- app/views/1-20/dynamic/add-address-confirmation.html
- app/views/1-20/dynamic/add-address-postcode.html
- app/views/1-20/dynamic/cancel-address.html
- app/views/1-20/dynamic/check-your-answers.html
- app/views/1-20/dynamic/confirmation.html
- app/views/1-20/dynamic/learner-details-requestpending.html
- app/views/1-20/dynamic/pages/no-addresses-1.html
- app/views/1-20/dynamic/pages/no-addresses-2.html
- app/views/1-20/dynamic/pages/no-addresses-3.html
- app/views/1-20/dynamic/pages/no-addresses-4.html
- app/views/includes/reviews-appeals/record-entry-no-core-specialism.html
- app/views/index.html
Copy updated, New 0 addresses page and changes to AO reviews and appeals journey
> 1-20 SoA and 1-19 AO changes

- app/views/1-20/dynamic/request-statement-of-achievement-already-requested.html
- app/views/1-20/dynamic/request-statement-of-achievement-check-and-submit.html
- app/views/1-20/dynamic/request-statement-of-achievement-not-available-no-results.html
- app/views/1-20/dynamic/request-statement-of-achievement.html
- check and submit
- request a statement
- statement already requested
-
> 1-20 SoA - Content updates

- app/routes.js
- app/views/1-20/dynamic/add-address-confirm-address.html
- app/views/1-20/dynamic/add-address-manually.html
- app/views/1-20/dynamic/add-address-select-address.html
- app/views/1-20/dynamic/org-address-present.html
- app/views/1-20/dynamic/request-statement-of-achievement-already-requested.html
- app/views/1-20/dynamic/request-statement-of-achievement-check-and-submit.html
> 1-20 Postal Address update

- app/routes.js
- app/views/1-20/dynamic/add-address-manually.html
- app/views/1-20/dynamic/request-statement-of-achievement-not-available-no-results.html
- Add in optional text next to Org name
> 1-20 Copy updates

- app/views/1-19/dynamic/core-put-on-appeal-2021.html
- app/views/1-19/dynamic/no-learner-found.html
- app/views/1-19/dynamic/record-entries-routes.html
- app/views/includes/reviews-appeals/record-entry-full-results-2021.html
Page Titles corrected and content in the Learner not found page updated
> 1-19 Reviews and Appeals Journey - Page Titles added

- app/views/1-19/dynamic/change-core-result-appeal-2021.html
- app/views/1-19/dynamic/core-put-on-appeal-2021.html
- app/views/1-19/dynamic/core-take-off-appeal-2021.html
- app/views/1-19/dynamic/no-learner-found.html
- app/views/includes/reviews-appeals/record-entry-full-results-2021.html
Updated error messages on core put on appeal, take off appeal and change core result pages
Updated no learner found page to remove link and replace with secondary button (Back to home)
> Error Messages & Learner not found button update

- app/assets/sass/application.scss
- app/routes.js
- app/views/1-19/dynamic/record-entries-routes.html
- app/views/includes/reviews-appeals/record-entry-full-results-2021.html
Replaced table with summary list and added media query breakpoint to change width of columns when at 930px
> Reviews and Appeals - Responsive Summary List

- app/routes.js
- app/views/1-19/dynamic/change-core-result-appeal-2021.html
- app/views/1-19/dynamic/change-core-result-appeal.html
- app/views/1-19/dynamic/change-specialism-result-appeal.html
- app/views/1-19/dynamic/change-specialism-result.html
- app/views/1-19/dynamic/check-result-change-appeal-2021.html
- app/views/1-19/dynamic/check-result-change-appeal.html
- app/views/1-19/dynamic/check-result-change.html
- app/views/1-19/dynamic/core-put-on-appeal-2021.html
- app/views/1-19/dynamic/core-put-on-appeal.html
- app/views/1-19/dynamic/core-put-on-hold.html
- app/views/1-19/dynamic/core-take-off-appeal-2021.html
- app/views/1-19/dynamic/core-take-off-appeal.html
- app/views/1-19/dynamic/core-take-off-hold.html
- app/views/1-19/dynamic/has-result-changed.html
- app/views/1-19/dynamic/specialism-check-result-change-appeal.html
- app/views/1-19/dynamic/specialism-check-result-change.html
- app/views/1-19/dynamic/specialism-has-result-changed.html
- app/views/1-19/dynamic/specialism-put-on-appeal-2021.html
- app/views/1-19/dynamic/specialism-put-on-appeal.html
- app/views/1-19/dynamic/specialism-put-on-hold.html
- app/views/1-19/dynamic/specialism-take-off-appeal.html
- app/views/1-19/dynamic/specialism-take-off-hold.html
- app/views/includes/record-entries-success-messages.html
- app/views/includes/reviews-appeals/record-entry-full-results-2021.html
- app/views/includes/reviews-appeals/record-entry-full-results.html
- Added in reviews and appeals (Autumn 2021) functionality
- Changed label components to legend and removed margin bottom-6
> 1-19 Reviews and Appeals - Adding in reviews functionality

- app/views/1-19/dynamic/access-denied.html
- app/views/1-19/dynamic/cancel-appeal-2021.html
- app/views/1-19/dynamic/check-result-change-appeal-2021.html
- app/views/1-19/dynamic/core-take-off-appeal.html
- app/views/index.html
- Added in restricted permissions page (content to be decided)
- Added in cancel page on check and submit (content to be decided)
> Design and Content changes 1-19 Reviews and Appeals

- app/routes.js
- app/views/1-19/dynamic/cancel-appeal-2021.html
- app/views/1-19/dynamic/check-result-change-appeal-2021.html
- app/views/1-19/dynamic/learner-withdrawn.html
- app/views/1-19/dynamic/no-assessment-entry.html
- app/views/1-19/dynamic/no-grades-to-appeal.html
- app/views/1-19/dynamic/record-entries-routes.html
- app/views/1-19/dynamic/select-component.html
- app/views/1-19/dynamic/select-exam-period.html
- app/views/includes/record-entries-success-messages.html
- Updated routes to add in additional pages for No Assessment entry, No grades yet to appeal, Select exam period and Select component
- Added in pages for above mentioned
> 1-19 Reviews and Appeals - Addition of Intermittent pages

- app/routes.js
- app/views/1-19/dynamic/check-result-change-appeal-2021.html
- app/views/1-19/dynamic/no-grades-to-appeal.html
- app/views/includes/exceptions/exceptions-option-other.html
- app/views/includes/exceptions/exceptions-select-option.html
- Removed select component page as specialism will not be registered until 2022
- Removed 'TEST' from heading copy on the no grades to appeal page
- Added in a line break that was missing on the check and submit page for provider row
> 1-19 Reviews and Appeals

- app/routes.js
- app/views/1-19/dynamic/registrations/registration-details-appeal.html
- app/views/1-19/dynamic/registrations/search-registration.html
- app/views/1-19/dynamic/registrations/student-registrations.html
- app/views/1-19/dynamic/results/learner-results-cannot-edit.html
- app/views/1-19/dynamic/results/search-learner.html
- app/views/1-19/dynamic/results/student-results.html
- app/views/1-19/dynamic/tlevels-dashboard.html
Added in content and screens for the registrations and results journey to cater for the "effects on the wider service"
> 1-19 Effects on the wider service

- app/views/1-19/dynamic/registrations/registration-cannot-be-withdrawn.html
- app/views/1-19/dynamic/registrations/registration-details-amend-options-active.html
- app/views/1-19/dynamic/registrations/registration-details-appeal-MVS.html
- app/views/1-19/dynamic/registrations/search-registration.html
- app/views/1-19/dynamic/results/learner-results-option-1.html
- app/views/1-19/dynamic/results/learner-results-option-2.html
Additional screens for effects on the wider service
- registration cannot be withdrawn
- learner results (final status) option 1
- learner results (final status) option 2
> 1-19 Effects on wider service

- app/routes.js
- app/views/1-19/dynamic/core-take-off-appeal-2021.html
- app/views/1-19/dynamic/exceptions/request-grade-change.html
- app/views/1-19/dynamic/record-entries-routes.html
- app/views/1-19/dynamic/registrations/student-registrations.html
- app/views/1-19/dynamic/results/results-no-learner-found.html
- Content updates to registrations dashboard
- Content updates to request grade change page
- Content updates to withdraw appeal journey
- Effects on wider service - added in learner not found page - to be consistent with Appeals part of service
> 1-19 Content updates & effects on wider service

- app/routes.js
- app/views/1-19/dynamic/exceptions/cancel-request-grade-change.html
- app/views/1-19/dynamic/exceptions/request-grade-change-confirmation.html
- app/views/1-19/dynamic/exceptions/request-grade-change.html
- app/views/1-19/dynamic/no-learner-found.html
- app/views/1-19/dynamic/record-entries-routes.html
- app/views/1-19/dynamic/registrations/register-new-learner.html
- app/views/1-19/dynamic/registrations/student-registrations.html
- app/views/1-19/dynamic/results/learner-results-final.html
- app/views/1-19/dynamic/results/results-no-learner-found.html
- app/views/1-19/dynamic/reviews-and-appeals.html
- app/views/includes/reviews-appeals/record-entry-full-results-2021.html
Content updates to the request a grade change journey
> 1-19 Request grade change content update

- app/views/1-19/dynamic/exceptions/request-grade-change-confirmation.html
-Content updates to the request grade change confirmation page
> Content updates - Request grade change confirmation

- app/routes.js
- app/views/1-19/dynamic/assessments/assessments-dashboard.html
- app/views/1-19/dynamic/exceptions/exceptions-process-confirmation.html
- app/views/1-19/dynamic/exceptions/exceptions-process-put-on-appeal.html
- app/views/1-19/dynamic/exceptions/exceptions-process.html
- app/views/1-19/dynamic/exceptions/request-grade-change-confirmation.html
- app/views/1-19/dynamic/record-entries-routes.html
- app/views/1-19/dynamic/registrations/student-registrations.html
- app/views/1-19/dynamic/registrations/upload-registrations-file.html
- app/views/1-19/dynamic/results/student-results.html
- app/views/1-19/dynamic/results/upload-results-file.html
Added in the exceptions process including content and routes
> 1-19 Exceptions

- app/assets/sass/application.scss
- app/routes.js
- app/views/1-19/dynamic/exceptions/exceptions-process-confirmation.html
- app/views/1-19/dynamic/t-levels/confirmed-t-levels.html
- app/views/1-19/dynamic/t-levels/queried-t-levels.html
- app/views/1-19/dynamic/t-levels/query-t-level-confirmation.html
- app/views/1-19/dynamic/t-levels/query-t-level.html
- app/views/1-19/dynamic/t-levels/review-t-levels-confirmation-reviews-complete.html
- app/views/1-19/dynamic/t-levels/review-t-levels-confirmation.html
- app/views/1-19/dynamic/t-levels/student-t-levels.html
- app/views/1-19/dynamic/t-levels/tlevel-all-reviewed.html
- app/views/1-19/dynamic/t-levels/tlevel-details-confirmed-1.html
- app/views/1-19/dynamic/t-levels/tlevel-details-confirmed.html
- app/views/1-19/dynamic/t-levels/tlevel-details-queried-1.html
- app/views/1-19/dynamic/t-levels/tlevel-details-queried.html
- app/views/1-19/dynamic/t-levels/tlevel-select-non-reviewed.html
- app/views/1-19/dynamic/t-levels/verify-tlevel-details.html
- app/views/1-19/dynamic/tlevels-dashboard.html
- Added in the new T levels journey in the AO side
- Includes new layout and amendments to journey
- Some content still to be confirmed/added
> 1-19 - Service Improvements - Added in T levels journey for AO

- app/routes.js
- app/views/1-19/dynamic/providers/providers-dashboard.html
- app/views/1-19/dynamic/registrations/add-registration-check-submit.html
- app/views/1-19/dynamic/registrations/add-registration-q1.html
- app/views/1-19/dynamic/registrations/add-registration-q2-name.html
- app/views/1-19/dynamic/registrations/add-registration-q3-dob.html
- app/views/1-19/dynamic/registrations/add-registration-q4-provider.html
- app/views/1-19/dynamic/registrations/add-registration-q5-core.html
- app/views/1-19/dynamic/registrations/add-registration-q6-specialism.html
- app/views/1-19/dynamic/registrations/add-registration-q7-year.html
- app/views/1-19/dynamic/registrations/register-new-learner.html
- app/views/1-19/dynamic/registrations/registration-already-registered.html
- app/views/1-19/dynamic/registrations/registration-cannot-be-found.html
- app/views/1-19/dynamic/registrations/registration-successful.html
- app/views/1-19/dynamic/tlevels-dashboard.html
- Added in the Register a new learner journey
- Content update and journey improvement
- Error validation required to be added still
> 1-19 Service Improvements - Register a new learner

- app/routes.js
- app/views/1-19/dynamic/assessments/upload-assessment-file.html
- app/views/1-19/dynamic/registrations/add-registration-check-submit.html
- app/views/1-19/dynamic/registrations/cancel-register-new-learner.html
- app/views/1-19/dynamic/registrations/registration-already-registered.html
- app/views/1-19/dynamic/registrations/registration-details-appeal-MVS.html
- app/views/1-19/dynamic/registrations/search-registration.html
- app/views/1-19/dynamic/registrations/upload-registrations-file.html
- app/views/1-19/dynamic/registrations/upload-successful.html
- app/views/1-19/dynamic/results/upload-results-file.html
- app/views/1-19/dynamic/t-levels/confirmed-t-levels.html
- app/views/1-19/dynamic/t-levels/queried-t-levels.html
- app/views/1-19/dynamic/t-levels/review-t-levels-confirmation-reviews-complete.html
- app/views/1-19/dynamic/t-levels/tlevel-all-reviewed.html
- app/views/1-19/dynamic/t-levels/tlevel-details-confirmed-1.html
- app/views/1-19/dynamic/t-levels/tlevel-details-confirmed.html
- app/views/1-19/dynamic/t-levels/tlevel-select-non-reviewed.html
content changes to T level pages
Beginning to add in manage registrations journey
> 1-19 - content changes - tlevels

- app/routes.js
- app/views/1-19/dynamic/registrations/change-dob.html
- app/views/1-19/dynamic/registrations/change-name.html
- app/views/1-19/dynamic/registrations/registration-details-appeal-MVS.html
- app/views/1-19/dynamic/registrations/search-registration.html
- app/views/1-19/dynamic/t-levels/query-t-level-confirmation.html
- app/views/1-19/dynamic/t-levels/query-t-level.html
- app/views/1-19/dynamic/t-levels/tlevel-details-confirmed-1.html
- app/views/1-19/dynamic/t-levels/tlevel-details-confirmed.html
- app/views/includes/registrations-success-messages.html
- Add in missing links and additional content
- Began adding in routes and pages for managing existing registration
> 1-19 T levels journey - adding in content and missing links
